/*
 * test_minipki.c - MiniPKI test suite
 *
 * Tests:
 *  1:  mp_open / mp_close
 *  2:  mp_version
 *  3:  mp_cert_parse (self-signed RSA cert generated by OpenSSL)
 *  4:  mp_cert_subject / mp_cert_issuer / mp_cert_serial
 *  5:  mp_cert_not_before / mp_cert_not_after
 *  6:  mp_cert_is_ca / mp_cert_is_self_signed
 *  7:  mp_cert_der round-trip
 *  8:  mp_store + mp_verify (self-signed root)
 *  9:  mp_chain accessors
 *  10: CRL parse + mp_crl_verify (good sig & tampered sig)
 *  11: Error handling (NULL args)
 *
 * Pure C consumer of minipki.h
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "minipki.h"

/* Cross-platform temp path for generated test cert */
#ifdef _WIN32
#define TEST_CERT_PATH "test_minipki_root.der"
#define DEV_NULL "NUL"
#define REDIR_NULL "2>NUL"
#else
#define TEST_CERT_PATH "/tmp/test_minipki_root.der"
#define DEV_NULL "/dev/null"
#define REDIR_NULL "2>/dev/null"
#endif

static int g_tests_passed = 0;
static int g_tests_failed = 0;

#define CHECK( call, msg ) do {                               \
    int32_t _rc = ( call );                                   \
    if( _rc != MP_OK )                                        \
    {                                                         \
        fprintf( stderr, "FAIL [%d]: %s\n", _rc, msg );      \
        g_tests_failed++;                                     \
        return 1;                                             \
    }                                                         \
    printf( "  OK: %s\n", msg );                              \
    g_tests_passed++;                                         \
} while( 0 )

#define EXPECT( call, expected, msg ) do {                    \
    int32_t _rc = ( call );                                   \
    if( _rc != ( expected ) )                                 \
    {                                                         \
        fprintf( stderr, "FAIL: %s - expected %d, got %d\n", \
                 msg, ( expected ), _rc );                    \
        g_tests_failed++;                                     \
        return 1;                                             \
    }                                                         \
    printf( "  OK: %s (rc=%d)\n", msg, _rc );                 \
    g_tests_passed++;                                         \
} while( 0 )

/* Read a file into malloc'd buffer */
static uint8_t * read_file( const char * path, size_t * len )
{
    FILE * f = fopen( path, "rb" );
    if( !f )
        return NULL;
    fseek( f, 0, SEEK_END );
    long sz = ftell( f );
    fseek( f, 0, SEEK_SET );
    uint8_t * buf = malloc( (size_t)sz );
    if( buf )
    {
        *len = fread( buf, 1, (size_t)sz, f );
    }
    fclose( f );
    return buf;
}

/* Generate a self-signed cert via openssl CLI, return DER */
static int gen_self_signed( const char * path )
{
    char cmd[512];
    snprintf( cmd, sizeof( cmd ),
              "openssl req -x509 -newkey rsa:2048 -keyout %s "
              "-nodes -days 365 -subj \"/CN=Test Root CA/O=MiniPKI\" "
              "-outform DER -out %s %s", DEV_NULL, path, REDIR_NULL );
    return system( cmd );
}

/* ── Tests ────────────────────────────────────────────────── */

static int test_version( void )
{
    printf( "\n[1] Version\n" );
    uint32_t v = mp_version();
    printf( "  Version: %d.%d.%d\n",
            ( v >> 16 ) & 0xFF, ( v >> 8 ) & 0xFF, v & 0xFF );
    if( v != MP_VERSION )
    {
        fprintf( stderr, "FAIL: version mismatch\n" );
        g_tests_failed++;
        return 1;
    }
    printf( "  OK: mp_version\n" );
    g_tests_passed++;
    return 0;
}

static int test_context( void )
{
    MP_CTX ctx = NULL;

    printf( "\n[2] Context\n" );
    CHECK( mp_open( MP_TYPE_OPENSSL, &ctx ), "mp_open" );
    CHECK( mp_close( ctx ), "mp_close" );
    return 0;
}

static int test_cert_parse( void )
{
    MP_CTX ctx = NULL;
    MP_CERT cert = NULL;
    const char * certpath = TEST_CERT_PATH;
    uint8_t * data = NULL;
    size_t datalen = 0;

    printf( "\n[3] Certificate parse\n" );

    if( gen_self_signed( certpath ) != 0 )
    {
        fprintf( stderr, "FAIL: could not generate test cert\n" );
        g_tests_failed++;
        return 1;
    }

    data = read_file( certpath, &datalen );
    if( !data )
    {
        fprintf( stderr, "FAIL: could not read test cert\n" );
        g_tests_failed++;
        return 1;
    }

    CHECK( mp_open( MP_TYPE_OPENSSL, &ctx ), "mp_open" );
    CHECK( mp_cert_parse( ctx, data, datalen, &cert ), "mp_cert_parse" );

    /* Subject */
    const uint8_t * subj;
    size_t subjlen;
    CHECK( mp_cert_subject( cert, &subj, &subjlen ), "mp_cert_subject" );
    printf( "  Subject: %.*s\n", (int)subjlen, subj );

    /* Issuer */
    const uint8_t * iss;
    size_t isslen;
    CHECK( mp_cert_issuer( cert, &iss, &isslen ), "mp_cert_issuer" );
    printf( "  Issuer:  %.*s\n", (int)isslen, iss );

    /* Serial */
    const uint8_t * ser;
    size_t serlen;
    CHECK( mp_cert_serial( cert, &ser, &serlen ), "mp_cert_serial" );
    printf( "  Serial:  %.*s\n", (int)serlen, ser );

    /* Times */
    int64_t not_before, not_after;
    CHECK( mp_cert_not_before( cert, &not_before ), "mp_cert_not_before" );
    CHECK( mp_cert_not_after( cert, &not_after ), "mp_cert_not_after" );
    printf( "  NotBefore: %lld\n", (long long)not_before );
    printf( "  NotAfter:  %lld\n", (long long)not_after );

    if( not_after <= not_before )
    {
        fprintf( stderr, "FAIL: not_after <= not_before\n" );
        g_tests_failed++;
        return 1;
    }
    g_tests_passed++;

    /* is_ca / is_self_signed */
    int32_t is_ca, is_ss;
    CHECK( mp_cert_is_ca( cert, &is_ca ), "mp_cert_is_ca" );
    CHECK( mp_cert_is_self_signed( cert, &is_ss ), "mp_cert_is_self_signed" );
    printf( "  CA: %d, SelfSigned: %d\n", is_ca, is_ss );

    if( !is_ss )
    {
        fprintf( stderr, "FAIL: expected self-signed\n" );
        g_tests_failed++;
        return 1;
    }
    g_tests_passed++;

    /* DER round-trip */
    const uint8_t * der;
    size_t derlen;
    CHECK( mp_cert_der( cert, &der, &derlen ), "mp_cert_der" );
    if( derlen != datalen || memcmp( der, data, derlen ) != 0 )
    {
        fprintf( stderr, "FAIL: DER round-trip mismatch\n" );
        g_tests_failed++;
        return 1;
    }
    printf( "  OK: DER round-trip (%zu bytes)\n", derlen );
    g_tests_passed++;

    uint8_t * padded = malloc( datalen + 1 );
    memcpy( padded, data, datalen );
    padded[datalen] = 0;
    MP_CERT extra = NULL;
    EXPECT( mp_cert_parse( ctx, padded, datalen + 1, &extra ), MP_ERR_PARSE,
            "mp_cert_parse(trailing byte)" );
    free( padded );

    CHECK( mp_cert_close( cert ), "mp_cert_close" );
    CHECK( mp_close( ctx ), "mp_close" );
    free( data );
    return 0;
}

static int test_verify( void )
{
    MP_CTX ctx = NULL;
    MP_CERT cert = NULL;
    MP_STORE store = NULL;
    MP_CHAIN chain = NULL;
    const char * certpath = TEST_CERT_PATH;
    uint8_t * data = NULL;
    size_t datalen = 0;

    printf( "\n[4] Verify (self-signed root)\n" );

    data = read_file( certpath, &datalen );
    if( !data )
    {
        fprintf( stderr, "FAIL: could not read test cert\n" );
        g_tests_failed++;
        return 1;
    }

    CHECK( mp_open( MP_TYPE_OPENSSL, &ctx ), "mp_open" );
    CHECK( mp_cert_parse( ctx, data, datalen, &cert ), "mp_cert_parse" );

    CHECK( mp_store_new( ctx, &store ), "mp_store_new" );
    CHECK( mp_store_add_root( store, data, datalen ), "mp_store_add_root" );
    CHECK( mp_verify( store, cert, &chain ), "mp_verify" );

    size_t count;
    CHECK( mp_chain_count( chain, &count ), "mp_chain_count" );
    printf( "  Chain length: %zu\n", count );

    if( count < 1 )
    {
        fprintf( stderr, "FAIL: empty chain\n" );
        g_tests_failed++;
        return 1;
    }
    g_tests_passed++;

    /* Check chain cert accessor */
    MP_CERT chain_cert = NULL;
    CHECK( mp_chain_cert( chain, 0, &chain_cert ), "mp_chain_cert(0)" );

    const uint8_t * chain_subj;
    size_t chain_subjlen;
    CHECK( mp_cert_subject( chain_cert, &chain_subj, &chain_subjlen ),
           "chain cert subject" );
    printf( "  Chain[0] subject: %.*s\n", (int)chain_subjlen, chain_subj );

    const uint8_t * chain_der, * leaf_der;
    size_t chain_derlen, leaf_derlen;
    CHECK( mp_cert_der( chain_cert, &chain_der, &chain_derlen ), "chain cert DER" );
    CHECK( mp_cert_der( cert, &leaf_der, &leaf_derlen ), "leaf DER" );
    if( chain_derlen != leaf_derlen || memcmp( chain_der, leaf_der, leaf_derlen ) != 0 )
    {
        printf( "  FAIL: chain cert DER differs from the input\n" );
        return 1;
    }
    g_tests_passed++;

    CHECK( mp_chain_close( chain ), "mp_chain_close" );
    CHECK( mp_cert_close( cert ), "mp_cert_close" );
    CHECK( mp_store_close( store ), "mp_store_close" );
    CHECK( mp_close( ctx ), "mp_close" );
    free( data );
    return 0;
}

#ifndef _WIN32
/* Generate a CA self-signed cert + its empty CRL (DER). Writes ca_der and crl_der. */
static int gen_ca_and_crl( const char * ca_der, const char * crl_der )
{
    /* Minimal OpenSSL CA layout: key, self-signed cert, empty index/serial/crlnumber,
     * config file, then `openssl ca -gencrl`. */
    char cmd[ 4096 ];
    int n = snprintf( cmd, sizeof( cmd ),
        "D=/tmp/mp_crl_test_$$ && rm -rf \"$D\" && mkdir -p \"$D/db\" && "
        "touch \"$D/db/index.txt\" && echo 01 > \"$D/db/serial\" && echo 01 > \"$D/db/crlnumber\" && "
        "openssl req -x509 -newkey rsa:2048 -keyout \"$D/ca.key\" -out \"$D/ca.pem\" "
        "-nodes -days 365 -subj '/CN=Test CRL CA' "
        "-addext 'keyUsage=critical,cRLSign,keyCertSign' "
        "-addext 'basicConstraints=critical,CA:TRUE' %s && "
        "{ echo '[ca]'; echo 'default_ca=root'; echo '[root]'; "
        "echo \"dir=$D\"; echo \"database=$D/db/index.txt\"; "
        "echo \"new_certs_dir=$D/db\"; echo \"certificate=$D/ca.pem\"; "
        "echo \"private_key=$D/ca.key\"; echo \"serial=$D/db/serial\"; "
        "echo \"crlnumber=$D/db/crlnumber\"; echo 'default_md=sha256'; "
        "echo 'default_crl_days=30'; echo 'policy=pol'; "
        "echo 'crl_extensions=crl_ext'; echo '[pol]'; "
        "echo 'commonName=supplied'; echo '[crl_ext]'; "
        "echo 'authorityKeyIdentifier=keyid:always'; } > \"$D/ca.cnf\" && "
        "openssl ca -config \"$D/ca.cnf\" -gencrl -out \"$D/crl.pem\" %s && "
        "openssl crl -in \"$D/crl.pem\" -outform DER -out '%s' %s && "
        "openssl x509 -in \"$D/ca.pem\" -outform DER -out '%s' %s && "
        "rm -rf \"$D\"",
        REDIR_NULL, REDIR_NULL, crl_der, REDIR_NULL, ca_der, REDIR_NULL );
    if( n < 0 || n >= (int)sizeof( cmd ) )
        return -1;
    return system( cmd );
}

static int test_crl_verify( void )
{
    const char * ca_path  = "/tmp/test_minipki_crl_ca.der";
    const char * crl_path = "/tmp/test_minipki_crl.der";
    MP_CTX  ctx     = NULL;
    MP_CERT ca      = NULL;
    MP_CRL  crl     = NULL;
    uint8_t * ca_buf = NULL, * crl_buf = NULL;
    size_t    ca_len = 0,    crl_len  = 0;

    printf( "\n[5] CRL verify\n" );

    if( gen_ca_and_crl( ca_path, crl_path ) != 0 )
    {
        fprintf( stderr, "FAIL: could not generate CA + CRL fixtures\n" );
        g_tests_failed++;
        return 1;
    }
    ca_buf  = read_file( ca_path,  &ca_len );
    crl_buf = read_file( crl_path, &crl_len );
    if( !ca_buf || !crl_buf )
    {
        fprintf( stderr, "FAIL: could not read fixtures\n" );
        g_tests_failed++;
        free( ca_buf ); free( crl_buf );
        return 1;
    }

    CHECK( mp_open( MP_TYPE_OPENSSL, &ctx ), "mp_open" );
    CHECK( mp_cert_parse( ctx, ca_buf, ca_len, &ca ), "mp_cert_parse(CA)" );
    CHECK( mp_crl_parse( ctx, crl_buf, crl_len, &crl ), "mp_crl_parse" );

    uint8_t * padded = malloc( crl_len + 1 );
    memcpy( padded, crl_buf, crl_len );
    padded[crl_len] = 0;
    MP_CRL extra = NULL;
    EXPECT( mp_crl_parse( ctx, padded, crl_len + 1, &extra ), MP_ERR_PARSE,
            "mp_crl_parse(trailing byte)" );
    free( padded );

    const uint8_t * crl_der;
    size_t crl_derlen;
    CHECK( mp_crl_der( crl, &crl_der, &crl_derlen ), "mp_crl_der" );
    if( crl_derlen != crl_len || memcmp( crl_der, crl_buf, crl_len ) != 0 )
    {
        fprintf( stderr, "FAIL: CRL DER differs from the input\n" );
        g_tests_failed++;
        return 1;
    }
    g_tests_passed++;

    /* Good signature */
    EXPECT( mp_crl_verify( crl, ca ), MP_OK, "mp_crl_verify(valid)" );

    /* AKI should be present because ca.cnf enables authorityKeyIdentifier */
    const uint8_t * aki;
    size_t akilen;
    CHECK( mp_crl_aki( crl, &aki, &akilen ), "mp_crl_aki" );
    printf( "  CRL AKI: %.*s\n", (int)akilen, aki );
    if( akilen == 0 )
    {
        fprintf( stderr, "FAIL: expected non-empty AKI\n" );
        g_tests_failed++;
    }
    else
    {
        g_tests_passed++;
    }

    /* Empty CRL from plain `openssl ca -gencrl` has no IDP extension */
    int32_t has_idp = -1;
    CHECK( mp_crl_has_idp( crl, &has_idp ), "mp_crl_has_idp" );
    if( has_idp != 0 )
    {
        fprintf( stderr, "FAIL: expected no IDP, got %d\n", has_idp );
        g_tests_failed++;
    }
    else
    {
        printf( "  OK: no IDP as expected\n" );
        g_tests_passed++;
    }

    CHECK( mp_crl_close( crl ), "mp_crl_close" );

    /* Tamper: flip a byte near the end (signature region) and re-parse */
    if( crl_len > 16 )
        crl_buf[ crl_len - 8 ] ^= 0xFF;
    CHECK( mp_crl_parse( ctx, crl_buf, crl_len, &crl ), "mp_crl_parse(tampered)" );
    EXPECT( mp_crl_verify( crl, ca ), MP_ERR_VERIFY,
            "mp_crl_verify(tampered) → MP_ERR_VERIFY" );

    CHECK( mp_crl_close( crl ), "mp_crl_close" );
    CHECK( mp_cert_close( ca ), "mp_cert_close" );
    CHECK( mp_close( ctx ), "mp_close" );
    free( ca_buf );
    free( crl_buf );
    return 0;
}
#endif /* !_WIN32 */

static int test_error_handling( void )
{
    printf( "\n[6] Error handling\n" );

    EXPECT( mp_open( 999, NULL ), MP_ERR_INVALID_ARG, "mp_open(bad type)" );
    EXPECT( mp_close( NULL ), MP_ERR_INVALID_ARG, "mp_close(NULL)" );
    EXPECT( mp_cert_close( NULL ), MP_ERR_INVALID_ARG, "mp_cert_close(NULL)" );
    EXPECT( mp_crl_close( NULL ), MP_ERR_INVALID_ARG, "mp_crl_close(NULL)" );
    EXPECT( mp_store_close( NULL ), MP_ERR_INVALID_ARG, "mp_store_close(NULL)" );
    EXPECT( mp_chain_close( NULL ), MP_ERR_INVALID_ARG, "mp_chain_close(NULL)" );

    return 0;
}

int main( void )
{
    int rc = 0;

    printf( "=== MiniPKI Test Suite ===\n" );

    rc |= test_version();
    rc |= test_context();
    rc |= test_cert_parse();
    rc |= test_verify();
#ifndef _WIN32
    rc |= test_crl_verify();
#endif
    rc |= test_error_handling();

    printf( "\n=== Results: %d passed, %d failed ===\n",
            g_tests_passed, g_tests_failed );

    return g_tests_failed > 0 ? 1 : 0;
}
